version: 2.1

orbs:
  node: circleci/node@5.0.2
  codecov: codecov/codecov@4.0.1

jobs:
  test:
    executor:
      name: node/default
      tag: 'current'
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Javascript Linter
          command: npm run lint
      - run:
          name: Unit tests with code coverage
          command: npm run test:unit:cov

workflows:
  node-tests:
    jobs:
      - test:
          post-steps:
            - codecov/upload
